---
name: ci
on:
  pull_request:
  push:
    branches:
      - 'release/**'
jobs:
  build-and-test:
    uses: NikitaSkrynnik/.github/.github/workflows/build-and-test.yaml@build-and-test
    with:
      os: '["ubuntu-latest", "macos-latest", "windows-latest"]'
      
  captureRunEnv:
    name: Capture CI Run Env
    runs-on: ubuntu-latest
    steps:
      - run: printenv
