---
name: Release
on:
  workflow_run:
    types:
      - completed
    workflows:
      - 'ci'
jobs:
  release:
    if: ${{ github.event.workflow_run.conclusion == 'success' && contains(github.event.workflow_run.head_branch, 'release/') }}
    uses: networkservicemesh/.github/.github/workflows/release.yaml@main
    with:
      dependent_repositories: |
        ["cmd-forwarder-vpp",
        "cmd-nsc-vpp",
        "cmd-nse-icmp-responder-vpp",
        "cmd-nse-vlan-vpp",
        "cmd-nse-firewall-vpp",
        "cmd-nse-vl3-vpp"]
    secrets:
      token: ${{ secrets.NSM_BOT_GITHUB_TOKEN }}
